baseURL = "https://gohugo.io"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "omniscient"
themesDir="../../"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"
    weight = 20


[[params.socials]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/"

[[params.socials]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/"

[[params.socials]]
icon = "fab fa-dev"
title = "Dev.to"
url = "https://dev.to/"

[[params.socials]]
icon = "fab fa-codepen"
title = "CodePen"
url = "https://codepen.io/"


[[params.socials]]
icon = "fas fa-envelope"
title = "Home"
url = "#"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
